apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'parasoft-dtp'
spec:
  project: default
  source:
    repoURL: >-
      replacement-url-here
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true